dist: trusty
sudo: false
cache:
  directories:
    - $HOME/.cache/pip

language: python

matrix:
  fast_finish: true

  include:
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
    - python: "pypy3.5-5.8.0"
      env: TOXENV=pypy3
    # Prevent breakage by a new release
    - python: "3.6-dev"
      env: TOXENV=py36
    - python: "3.7-dev"
      env: TOXENV=py37

  allow_failures:
    python: "3.6-dev"
    python: "3.7-dev"

install:
  - pip install tox

script:
  - tox
